### ISSUE TITLE
Porting to OSX

### ISSUE THREAD

**Issue by ctrlrsf** [skarmoutsosv/LiveWB#4]
Here are some notes/hints for porting this to OSX if anybody is interested.

`gsettings set` Gnome command could be accomplished with:

```
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"${STOREFILE}\""
```

ImageMagick commands (`convert`/`composite`) could be installed from brew using `brew install imagemagick`

wget could be installed with `brew install wget`, or instead `curl` could be used to fetch images.

**Comment by skarmoutsosv** [comment]
It will be intersting to see LiveWB on OSX.
