### ISSUE TITLE
Not working with Mate

### ISSUE THREAD

**Issue by Joker701** [skarmoutsosv/LiveWB#5]
Downloaded and installed per install.readme, creates pictures and runs but doesn't change desktop background, I'm on Debian stretch.﻿ Using Mate DE.

**Comment by skarmoutsosv** [comment]
Hello Frank, I have just added some support for MATE.

You should now use the new code and check two things:
- Does LiveWB sets the image on your background?
- Does LiveWB updates to the next image?

If there is still a problem, please let me know.

**Comment by skarmoutsosv** [comment]
Useful sources about desktop environments:
http://peterlevi.com/variety/wiki/Script_xfce_three_monitor and
http://yabb.jriver.com/interact/index.php?topic=83217.msg687513#msg687513

**Comment by Joker701** [comment]
Works fine now, thanks much.
